import type {Metadata} from "next";
import {DM_Sans} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import Provider from "@/components/dark-light-mode/Provider";

// Using DM_Sans as a free alternative to Google Sans
const dmSans = DM_Sans({
    variable: "--font-dm-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: LayoutProps<"/">) {
    return (
        <html
            lang="en"
            className={`${dmSans.variable} h-full antialiased`}
            suppressHydrationWarning={true}
        >
        <body className="min-h-full flex flex-col font-sans bg-background text-foreground">
        <Provider>
            <Navbar/>
            {children}
            <Footer/>
        </Provider>
        </body>
        </html>
    );
}